class Testdata:
    CHROME_EXECUTABLE_PATH = r"C:/self_automation_Swag_labs/browsers/chromedriver.exe"
    FIREFOX_EXECUTABLE_PATH = r"C:/self_automation_project1/browsers/geckodriver.exe"

    BASE_URL = "https://www.saucedemo.com/"
    username = "standard_user"
    password = "secret_sauce"
    login_page_title = "Swag Labs"
    product_page_text = "Products"
    shopping_cart_page_text = "Your Cart"
    product_backpack = "Sauce Labs Backpack"
    product_back_light = "Sauce Labs Bike Light"
    backpack_product_price = "$29.99"
    checkout_page_text = "Checkout: Your Information"
    address_first_name = "Vedant"
    address_last_name = "M"
    address_postal = "43001"
    checkout_overview_page_text = "Checkout: Overview"
    checkout_complete_text = "Checkout: Complete!"
    order_complete_text = "Thank you for your order!"

    # home_page_title = "User Guide | HubSpot"
    # home_page_header = "User Guides"
    # account_name = "googlr"